name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]   # Ejecuta diariamente
  workflow_dispatch:                # Permite ejecución manual
  push: {branches: ["master", "main"]} # Opcional: ejecuta al hacer push

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
